return {
	"WhoIsSethDaniel/mason-tool-installer.nvim",
	opts = {
		ensure_installed = {
			"standardrb",
			"prettier",
			"prettierd",
			"ktlint",
			"eslint_d",
			"google-java-format",
			"htmlbeautifier",
			"beautysh",
			"buf",
			"rustfmt",
			"yamlfix",
			"taplo",
			"shellcheck",
			"gopls",
			"delve",
			"astro-language-server",
			"stylua",
			"lua_ls",
		},
	},
}
