return {
	"WhoIsSethDaniel/mason-tool-installer.nvim",
	opts = {
		ensure_installed = {
			-- "angular-language-server",
			"astro-language-server",
			"bash-language-server",
			"beautysh",
			"buf",
			"cucumber-language-server",
			"delve",
			"dockerfile-language-server",
			"docker-compose-language-service",
			"doctoc",
			"emmet-ls",
			"eslint_d",
			"google-java-format",
			"gopls",
			-- "hadolint",
			"htmlbeautifier",
			-- "java-debug-adapter",
			-- "java-test",
			"jdtls",
			"json-lsp",
			"kotlin-language-server",
			"ktlint",
			"lua-language-server",
			"marksman",
			"prettier",
			"prettierd",
			-- "python-lsp-server",
			"pyright",
			"ruff",
			-- "rustfmt",
			"shellcheck",
			"solargraph",
			"sonarlint-language-server",
			"standardrb",
			-- "stylua",
			"superhtml",
			-- "tailwindcss-language-server",
			"taplo",
			"yamlfmt",
		},
	},
}
