return {
	"WhoIsSethDaniel/mason-tool-installer.nvim",
	opts = {
		ensure_installed = {
			"astro-language-server",
			"bash-language-server",
			"beautysh",
			"buf",
			"cucumber-language-server",
			"delve",
			"dockerfile-language-server",
      "emmet-ls",
			"eslint_d",
			"google-java-format",
			"gopls",
			"htmlbeautifier",
			"java-debug-adapter",
			"java-test",
			"jdtls",
			"json-lsp",
			"kotlin-language-server",
			"ktlint",
			"lua-language-server",
			"marksman",
			"prettier",
			"prettierd",
			"python-lsp-server",
			-- "rustfmt",
			"shellcheck",
			"solargraph",
			"stylua",
			-- "tailwindcss-language-server",
			"taplo",
			-- "yamlfix",
		},
	},
}
